version: "3.8"

services:
    redis:
        image: redis:7-alpine
        container_name: trading_redis
        ports:
            - "6379:6379"
        command: redis-server --requirepass ${REDIS_PASSWORD:-redispass}
        volumes:
            - redis_data:/data
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD:-redispass}
        restart: unless-stopped
        networks:
            - trading_network

    postgres:
        image: postgres:15-alpine
        container_name: trading_postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${DB_USER:-postgres}
            - POSTGRES_PASSWORD=${DB_PASSWORD:-postgrespass}
            - POSTGRES_DB=trading_db
            - TZ=Asia/Seoul
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init/db:/docker-entrypoint-initdb.d
        restart: unless-stopped
        networks:
            - trading_network

volumes:
    redis_data:
    postgres_data:

networks:
    trading_network:
        driver: bridge
